apiVersion: v1
kind: Service
metadata:
  labels:
      app: nginx
      tool: skaffold
  name: kubetest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
#  type: NodePort
  type: LoadBalancer
  selector:
    run: kubetest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kubetest
  name: kubetest
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubetest
  strategy: {}
  template:
    metadata:
      labels:
        run: kubetest
    spec:
      containers:
      - image: amitkarpe/nginx:latest
#        imagePullPolicy: Never
        name: kubetest
        ports:
        - containerPort: 80
