---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: s3
    app: s3
  name: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: s3
  template:
    metadata:
      labels:
        run: s3
        app: s3
    spec:
      serviceAccountName: s3
      containers:
      - image: amitkarpe/skaffold:latest
#        imagePullPolicy: Never
        name: aws
