apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: nginx-
build:
  artifacts:
    - image: amitkarpe/nginx
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - k8s-pod.yaml
