apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: kubetest
build:
  artifacts:
    - image: amitkarpe/nginx
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - k8s-pod.yaml
